---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune
spec:
  selector:
    matchLabels:
      app: fortune
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - name: fortune
        image: alexkaydocker/flask-fortune:stable
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fortune
spec:
  type: NodePort
  selector:
    app: fortune
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: fortune-ingress
  namespace: alex
spec:
  rules:
  - host: alex-fortune.kubelab.spainip.es
    http:
      paths:
      - backend:
          service:
            name: fortune
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - alex-fortune.kubelab.spainip.es
    secretName: tls-fortune-ingress