---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune
spec:
  selector:
    matchLabels:
      app: fortune
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - name: fortune
        image: alexkaydocker/flask-fortune:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fortune
spec:
  type: NodePort
  selector:
    app: fortune
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80