---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune
spec:
  selector:
    matchLabels:
      app: fortune
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - name: fortune
        image: alexkaydocker/flask-fortune:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fortune
spec:
  type: NodePort
  selector:
    app: fortune
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
# ---
# apiVersion: networking.k8s.io/v1
# kind: IngressClass
# metadata:
#   name: external-lb
# spec:
#   controller: example.com/ingress-controller
#   parameters:
#     apiGroup: k8s.example.com
#     kind: IngressParameters
#     name: external-lb
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: fortune-ingress
# spec:
#   defaultBackend:
#     service:
#       name: fortune
#       port:
#         number: 80