---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: fortune
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: fortune
        tier: backend
        track: stable
    spec:
      containers:
        - name: fortune
          image: "alexkaydocker/fortune:latest"
          ports:
            - name: http
              containerPort: 80
